version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  board1:
    build:
      context: ./server
    container_name: whiteboard_app_1
    environment:
      - INSTANCE_NAME=whiteboard_app_1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "5001:8080"

  board2:
    build:
      context: ./server
    container_name: whiteboard_app_2
    environment:
      - INSTANCE_NAME=whiteboard_app_2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "5002:8080"

  board3:
    build:
      context: ./server
    container_name: whiteboard_app_3
    environment:
      - INSTANCE_NAME=whiteboard_app_3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "5003:8080"
